package com.app7soft.currencyconverter

fun FlagaResource(s: String): Int{
    when (s) {
        "AED"-> return R.drawable.aed
        "AFN"-> return R.drawable.afn
        "ALL"-> return R.drawable.all
        "AMD"-> return R.drawable.amd
        "ANG"-> return R.drawable.ang
        "AOA"-> return R.drawable.aoa
        "ARS"-> return R.drawable.ars
        "AUD"-> return R.drawable.aud
        "AWG"-> return R.drawable.awg
        "AZN"-> return R.drawable.azn
        "BAM"-> return R.drawable.bam
        "BBD"-> return R.drawable.bbd
        "BDT"-> return R.drawable.bdt
        "BGN"-> return R.drawable.bgn
        "BHD"-> return R.drawable.bhd
        "BIF"-> return R.drawable.bif
        "BMD"-> return R.drawable.bmd
        "BND"-> return R.drawable.bnd
        "BOB"-> return R.drawable.bob
        "BRL"-> return R.drawable.brl
        "BSD"-> return R.drawable.bsd
        "BTC"-> return R.drawable.btc
        "BTN"-> return R.drawable.btn
        "BWP"-> return R.drawable.bwp
        "BYN"-> return R.drawable.byn
        "BYR"-> return R.drawable.byr
        "BZD"-> return R.drawable.bzd
        "CAD"-> return R.drawable.cad
        "CDF"-> return R.drawable.cdf
        "CHF"-> return R.drawable.chf
        "CLF"-> return R.drawable.clf
        "CLP"-> return R.drawable.clp
        "CNY"-> return R.drawable.cny
        "COP"-> return R.drawable.cop
        "CRC"-> return R.drawable.crc
        "CUC"-> return R.drawable.cuc
        "CUP"-> return R.drawable.cup
        "CVE"-> return R.drawable.cve
        "CZK"-> return R.drawable.czk
        "DJF"-> return R.drawable.djf
        "DKK"-> return R.drawable.dkk
        "DOP"-> return R.drawable.dop
        "DZD"-> return R.drawable.dzd
        "EGP"-> return R.drawable.egp
        "ERN"-> return R.drawable.ern
        "ETB"-> return R.drawable.etb
        "EUR"-> return R.drawable.eur
        "FJD"-> return R.drawable.fjd
        "FKP"-> return R.drawable.fkp
        "GBP"-> return R.drawable.gbp
        "GEL"-> return R.drawable.gel
        "GGP"-> return R.drawable.ggp
        "GHS"-> return R.drawable.ghs
        "GIP"-> return R.drawable.gip //tu zacząłem robić lepsza jakość 160
        "GMD"-> return R.drawable.gmd
        "GNF"-> return R.drawable.gnf
        "GTQ"-> return R.drawable.gtq
        "GYD"-> return R.drawable.gyd
        "HKD"-> return R.drawable.hkd
        "HNL"-> return R.drawable.hnl
        "HRK"-> return R.drawable.hrk
        "HTG"-> return R.drawable.htg
        "HUF"-> return R.drawable.huf
        "IDR"-> return R.drawable.idr
        "ILS"-> return R.drawable.ils
        "IMP"-> return R.drawable.imp
        "INR"-> return R.drawable.inr
        "IQD"-> return R.drawable.iqd
        "IRR"-> return R.drawable.irr
        "ISK"-> return R.drawable.isk
        "JEP"-> return R.drawable.jep
        "JMD"-> return R.drawable.jmd
        "JOD"-> return R.drawable.jod
        "JPY"-> return R.drawable.jpy
        "KES"-> return R.drawable.kes
        "KGS"-> return R.drawable.kgs
        "KHR"-> return R.drawable.khr
        "KMF"-> return R.drawable.kmf
        "KPW"-> return R.drawable.kpw
        "KRW"-> return R.drawable.krw
        "KWD"-> return R.drawable.kwd
        "KYD"-> return R.drawable.kyd
        "KZT"-> return R.drawable.kzt
        "LAK"-> return R.drawable.lak
        "LBP"-> return R.drawable.lbp
        "LKR"-> return R.drawable.lkr
        "LRD"-> return R.drawable.lrd
        "LSL"-> return R.drawable.lsl
        "LTL"-> return R.drawable.ltl
        "LVL"-> return R.drawable.lvl
        "LYD"-> return R.drawable.lyd
        "MAD"-> return R.drawable.mad
        "MDL"-> return R.drawable.mdl
        "MGA"-> return R.drawable.mga
        "MKD"-> return R.drawable.mkd
        "MMK"-> return R.drawable.mmk
        "MNT"-> return R.drawable.mnt
        "MOP"-> return R.drawable.mop
        "MRO"-> return R.drawable.mro
        "MUR"-> return R.drawable.mur
        "MVR"-> return R.drawable.mvr
        "MWK"-> return R.drawable.mwk
        "MXN"-> return R.drawable.mxn
        "MYR"-> return R.drawable.myr
        "MZN"-> return R.drawable.mzn
        "NAD"-> return R.drawable.nad
        "NGN"-> return R.drawable.ngn
        "NIO"-> return R.drawable.nio
        "NOK"-> return R.drawable.nok
        "NPR"-> return R.drawable.npr
        "NZD"-> return R.drawable.nzd
        "OMR"-> return R.drawable.omr
        "PAB"-> return R.drawable.pab
        "PEN"-> return R.drawable.pen
        "PGK"-> return R.drawable.pgk
        "PHP"-> return R.drawable.php
        "PKR"-> return R.drawable.pkr
        "PLN"-> return R.drawable.pln
        "PYG"-> return R.drawable.pyg
        "QAR"-> return R.drawable.qar
        "RON"-> return R.drawable.ron
        "RSD"-> return R.drawable.rsd
        "RUB"-> return R.drawable.rub
        "RWF"-> return R.drawable.rwf
        "SAR"-> return R.drawable.sar
        "SBD"-> return R.drawable.sbd
        "SCR"-> return R.drawable.scr
        "SDG"-> return R.drawable.sdg
        "SEK"-> return R.drawable.sek
        "SGD"-> return R.drawable.sgd
        "SHP"-> return R.drawable.shp
        "SLL"-> return R.drawable.sll
        "SOS"-> return R.drawable.sos
        "SRD"-> return R.drawable.srd
        "STD"-> return R.drawable.std
        "SVC"-> return R.drawable.svc
        "SYP"-> return R.drawable.syp
        "SZL"-> return R.drawable.szl
        "THB"-> return R.drawable.thb
        "TJS"-> return R.drawable.tjs
        "TMT"-> return R.drawable.tmt
        "TND"-> return R.drawable.tnd
        "TOP"-> return R.drawable.top
        "TRY"-> return R.drawable.tryy
        "TTD"-> return R.drawable.ttd
        "TWD"-> return R.drawable.twd
        "TZS"-> return R.drawable.tzs
        "UAH"-> return R.drawable.uah
        "UGX"-> return R.drawable.ugx
        "USD"-> return R.drawable.usd
        "UYU"-> return R.drawable.uyu
        "UZS"-> return R.drawable.uzs
        "VEF"-> return R.drawable.vef
        "VND"-> return R.drawable.vnd
        "VUV"-> return R.drawable.vuv
        "WST"-> return R.drawable.wst
        "XAF"-> return R.drawable.xaf
        "XAG"-> return R.drawable.xag
        "XAU"-> return R.drawable.xau
        //"XCD"-> return R.drawable.xcd
        //"XDR"-> return R.drawable.xdr
        //"XOF"-> return R.drawable.xof
        //"XPF"-> return R.drawable.xpf
        "YER"-> return R.drawable.yer
        "ZAR"-> return R.drawable.zar
        //"ZMK"-> return R.drawable.zmk to jest stare jakieś
        "ZMW"-> return R.drawable.zmw
        "ZWL"-> return R.drawable.zwl
    }
    return 0
}